# VEDA AI & ML Internship – Day 19
## Filter Dataset Records Using Pandas

**Objective:**  
Filter dataset records using one or more conditions with Pandas.

**Tools:** Python, Pandas, Jupyter Notebook

In [1]:
import pandas as pd

## 1. Load the Titanic Dataset

The Titanic dataset contains passenger information such as age, gender,
passenger class, fare, and survival status.

In [2]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset Shape: (891, 12)

Columns:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

## 2. Filter Passengers Based on Age

We can use a condition to retrieve passengers whose age is greater than 30.

In [4]:
age_filtered = df[df["Age"] > 30]

age_filtered.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

**Condition:** `Age > 30`

This retrieves only passengers whose age is greater than 30.

## 3. Filter Passengers Based on Gender

We can filter the dataset to retrieve only female passengers.

In [5]:
female_passengers = df[df["Sex"] == "female"]

female_passengers.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

**Condition:** `Sex == "female"`

This retrieves only the records where the passenger's gender is female.

## 4. Filter Using Multiple Conditions

Pandas allows multiple conditions using `&`.

Here, we retrieve passengers who are female and older than 30.

In [6]:
female_above_30 = df[(df["Sex"] == "female") & (df["Age"] > 30)]

female_above_30.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S

**Conditions:**
- Passenger must be female
- Passenger must be older than 30

The `&` operator means both conditions must be satisfied.
Parentheses are used around each condition.

## 5. Filter Passengers Based on Passenger Class and Fare

Retrieve passengers from first class who paid a fare greater than 50.

In [7]:
first_class_high_fare = df[
    (df["Pclass"] == 1) & (df["Fare"] > 50)
]

first_class_high_fare.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C

**Conditions:**
- Passenger class must be 1
- Fare must be greater than 50

The `&` operator combines both conditions.

## 6. Using OR Condition

The `|` operator is used when either of the conditions can be true.

Here, we retrieve passengers who are either in first class or second class.

In [8]:
first_or_second_class = df[
    (df["Pclass"] == 1) | (df["Pclass"] == 2)
]

first_or_second_class.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

## 7. Check the Number of Filtered Records

The `shape` attribute can be used to determine how many records satisfy
each filtering condition.

In [9]:
print("Age > 30:", len(age_filtered))
print("Female passengers:", len(female_passengers))
print("Female and Age > 30:", len(female_above_30))
print("First class and Fare > 50:", len(first_class_high_fare))
print("First or Second class:", len(first_or_second_class))

Age > 30: 305
Female passengers: 314
Female and Age > 30: 103
First class and Fare > 50: 139
First or Second class: 400

## Conclusion

In this task, Pandas filtering was used to retrieve relevant records from
the Titanic dataset.

### Filtering techniques learned:
- Single-condition filtering using `>`
- Equality filtering using `==`
- Multiple conditions using `&`
- OR conditions using `|`
- Parentheses for combining multiple conditions
- Checking the number of filtered records using `len()` and `shape`

Pandas filtering helps extract specific records from large datasets
efficiently.

nterview Questions
1. How do you filter rows in Pandas?
df[df["Age"] > 30]

This selects rows where the Age column is greater than 30.

2. How do you combine multiple conditions?

Use & for AND and | for OR.

df[(df["Age"] > 30) & (df["Sex"] == "female")]
3. Why are parentheses important?

Each condition should be enclosed in parentheses when combining conditions:

(df["Age"] > 30) & (df["Sex"] == "female")

This ensures Pandas evaluates the conditions correctly.

# 🎯 Interview Questions

## 1. How do you filter rows in Pandas?

`df[df["Age"] > 30]`

This selects rows where the `Age` column is greater than 30.

## 2. How do you combine multiple conditions?

Use `&` for **AND** and `|` for **OR**.

`df[(df["Age"] > 30) & (df["Sex"] == "female")]`

## 3. Why are parentheses important?

Each condition should be enclosed in parentheses when combining conditions:

`(df["Age"] > 30) & (df["Sex"] == "female")`

This ensures Pandas evaluates the conditions correctly.